### ISSUE TITLE
Method to save the model

### ISSUE THREAD

**Issue by YuliangXiaoYLX** [morphomatics/morphomatics#4]
Hi authors, currently I constructed an SSM model and wanted to save it. I already tried ```pickle```, ```h5py```, ```dill```, all of them did not work. Do you have any suggestions about how to save SSM object?
Thanks in advance!

**Comment by vontycowicz** [comment]
Dear Yuliang,

we do not provide explicit routines for saving/loading of SSMs. That said, the `StatisticalShapeModel` class implements only the construction of shape models and, once computed, does not offer much except for the determined quantities. At this point, you should be able to save/load those easily (they are `jax` arrays and can be converted to/from `numpy`). If you want to work with the loaded arrays, you will also have to instantiate the underlying shape space again using the loaded `SSM.mean` and the same construction method (i.e. `shape_space_cstr` passed during instantiation of `StatisticalShapeModel`).

Let me know if you run into further problems.

Best,
Christoph
